### PR TITLE
Update screenshots with Alpenglow

### PR DESCRIPTION
**Pull request by vikjam**
Partially addresses Issue #1. Updates the following with Alpenglow in the text:

screenshots/Alpenglow-blue.png 
screenshots/Alpenglow-default.png 
screenshots/Alpenglow-green.png 
screenshots/Alpenglow-inactive-tabs.png 
screenshots/Alpenglow-magenta.png 
screenshots/Alpenglow-markdown.png 
screenshots/Alpenglow-monokai.png 
screenshots/Alpenglow-orange.png 
screenshots/Alpenglow-twilight.png 

Need to still fix:

screenshots/Alpenglow-sidebar-row-padding.png
screenshots/Alpenglow-sidebar-size.png
screenshots/Alpenglow-tabs.png

### CODE REVIEW

**Comment by bmcminn** [comment]
Great work @vikjam, how much more effort do you think the last three graphic updates would take? I would like to bring everything in one merge to properly close #1

**Comment by vikjam** [comment]
Not too much effort--I'll just go ahead and finish out the last few.

**Comment by vikjam** [comment]
All done!

**Comment by bmcminn** [comment]
Very nice :)

**Comment by vikjam** [comment]
Eek! I forgot [one](https://github.com/vikjam/alpenglow-theme/blob/master/screenshots/Alpenglow-tabs.png). How should I submit it? Sorry about that!

**Comment by bmcminn** [comment]
I would just issue another PR and reference this one #6

**Pull request merged**
